fix(rules): fix no-unused-vars rule and add ignoreRestSiblings
SoftboxLab/gandalf-lint pull request #13
Opened 2019-04-12 13:30 UTC by vilaboim

2019-04-15 11:38 UTC, marlonmleite requested changes

2019-04-15 11:38 UTC, marlonmleite commented on rules/gandalf.js
> +    'no-unused-vars': ['error', { 'ignoreRestSiblings': true }],
Essas 2 opções "vars": "all" e "args": "after-used" como são default, o eslint continua usando elas com esse valor né?

2019-04-15 12:02 UTC, vilaboim commented on rules/gandalf.js
> +    'no-unused-vars': ['error', { 'ignoreRestSiblings': true }],
Pelos testes que fiz sim, pois removi as opções que tinham valor default e as regras continuaram valendo.

2019-04-16 04:38 UTC, pablohpsilva approved these changes

2019-04-16 04:39 UTC, pablohpsilva commented
@marlonmleite it looks OK for me as well.

2019-04-18 13:22 UTC, merged