Adicionando regras para padronização de import/export
SoftboxLab/gandalf-lint pull request #15
Opened 2019-04-25 15:41 UTC by marlonmleite

Algumas regras foram baseadas no eslint base do Airbnb e outras regras melhoradas conforme o uso nos projetos: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js

2019-05-16 14:04 UTC, rafael1995 submitted a review, later dismissed

2019-05-16 14:09 UTC, hugonasciutti submitted a review, later dismissed

2019-05-16 15:20 UTC, vilaboim requested changes

2019-05-16 15:20 UTC, vilaboim commented on rules/gandalf.js
> +    //import rules
Pode remover esse comentário.

2019-05-16 15:20 UTC, vilaboim commented on rules/gandalf.js
> +    'import/imports-first': 'off',
Essa regra foi depreciada - [link](https://github.com/benmosher/eslint-plugin-import/blob/4620185d0aa93da9675afb73ec713f5b1c821051/CHANGELOG.md#changed-4)

2019-05-16 15:20 UTC, vilaboim commented on rules/gandalf.js
> +          'internal'
Coloque as outras opções também para a regra para ficar explícita (sibling e index).

2019-05-16 15:20 UTC, vilaboim commented on rules/gandalf.js
> +    'import/no-internal-modules': ['off', { 'allow': [] }],
É necessário passar as options quando a regra está desativada? (isso vale para a regra abaixo)

2019-05-16 15:20 UTC, vilaboim commented on rules/gandalf.js
> +    'import/no-useless-path-segments': 'error',
Pode ser uma boa ideia adicionar a option `noUselessIndex` a essa regra.

2019-08-01 12:14 UTC, hugonasciutti submitted a review, later dismissed

2019-08-01 13:44 UTC, vilaboim requested changes

2019-08-01 13:44 UTC, vilaboim commented on rules/gandalf.js
>      'import/no-anonymous-default-export': ['off',
Faltou remover as opções desta regra, que também está desativada.

2019-08-01 14:12 UTC, vilaboim approved these changes

2019-08-01 14:12 UTC, merged